### ISSUE TITLE
Unable to connect to webserver

### ISSUE THREAD

**Issue by g78** [OWASP/crAPI#18]
Hi,

I followed the instructions to clone the repository, the docker install then run it in docker but I am unable to connect to the web server on port 8888.

I can connect to the mail client on port 8025.

I've run netstat -antp and port 8888 is listening but when I try and connect either using firefox or curl the connection is refused.

**Comment by dravadhis** [comment]
Hi!
I faced the same error after running the deploy command. Fixed it by following the below steps:
1. Navigate to `crAPI/deploy/docker/` and open `docker-compose.yml`. 
2. Scroll through the file and uncomment the wherever you see a ports reference. (ports for all services have been commented for some reason). Save the file and exit.
3. Don't run the deploy command right now since the `postgresdb` container wil conflict with the postgresql installed on your system. First run `sudo service postgresql status` to check whether postgres is running or not. If it is running, stop it using this command, `sudo service postgresql stop`. 
4. Now run the deploy command, `docker-compose -f deploy/docker/docker-compose.yml --compatibility up -d`.

These steps worked for my system (OS: Ubuntu 20.04 LTS). 

If it's not working even after all this, run the deploy command and inspect the containers using `docker inspect <container_name>`. The command lists whether a container is running and healthy. If it isn't, check the container logs whose location is mentioned somewhere in the output of the `docker inspect` command. For container names, refer to the `docker-compose.yml` file.

Regards

**Comment by vdvcoder** [comment]
Also worked for me on Macbook Air M1

**Comment by Beoas** [comment]
I have same problem but my port 8888 isn't listening when I tried netstat -antp  but my port 8025 is listening... I tried to uncomment everywhere I see ports but it as to be commented before it can run.

**Comment by razvan22** [comment]
Hi ! I just installed crAPI  and it works on http://localhost:8888 but no if i use the ip http://192.168.0.107:8888 , i want to access it from another machine it works with Juice Shop any suggestions?

**Comment by vtnrd** [comment]
To find the 'docker-compose.yml config file':

1. run sudo docker ps and note the container ID associated with 'crapi-web'
2. Run sudo docker inspect <container ID> | grep com.docker.compose
3. Note the path of the file in the line that reads "com.docker.compose.project.config_files": "/home/<user>/docker-compose.yml",
4. cat '/home/<user>/docker-compose.yml' to view the config file.

**Comment by vtnrd** [comment]
> Hi ! I just installed crAPI and it works on http://localhost:8888 but not by ip ex:http://192.168.0.107:8888 , i want to access it from another machine it works with Juice Shop any suggestions?

https://github.com/OWASP/crAPI/issues/18#issuecomment-1251197047

**Comment by victorwaldron** [comment]
Hello, I installed craPI and I can open both http://localhost:8888 and http://localhost:8025/#, but when I try to register in craPI, and put the password and also use the one suggested by the system, this one by More than I change the password, I still get this message: Password should contain at least one digit, one small letter and one capital letter and should at least contain 8 characters.
I don't understand why it won't let me register.
Any suggestion for that?
Thank you
![crapi singup](https://user-images.githubusercontent.com/69227013/204105283-6f231e27-4320-4806-8efb-ce2772a28c87.png)

**Comment by monrax** [comment]
Hello @victorwaldron , I was facing the same issue. Turns out [the password validation regex](https://github.com/OWASP/crAPI/blob/develop/services/web/src/constants/constants.js#L21) looks for one of the following symbols besides what the message states: #$@!%&*? Hope this helps!

**Comment by elcreek** [comment]
@monrax, thank you

**Comment by ebell451** [comment]
The Docker compose file is written to use 127.0.0.1 unless another value is supplied via an environment variable with the name LISTEN_IP. You can edit the .env file and change 127.0.0.1 with the IP address of your host machine.

<img width="575" alt="image" src="https://github.com/user-attachments/assets/fd4e9b6a-8a98-4a98-b44d-21b67ae69397">
