### ISSUE TITLE
Profile Picture image not loading on Community Forum

### ISSUE THREAD

**Issue by topher12093** [OWASP/crAPI#6]
Hi!

I'm able to change my profile picture on the my-profile page. However, when I then comment on a post on the Community page and/or create a new post, I'm not seeing my profile picture load. Is this a bug? Part of any challenge?

Thanks!
Chris

Running in docker
<img width="1634" alt="Screen Shot 2021-04-28 at 1 50 07 PM" src="https://user-images.githubusercontent.com/8628929/116457235-c1e37680-a828-11eb-9cc7-3b440099e994.png">
<img width="1396" alt="Screen Shot 2021-04-28 at 1 50 29 PM" src="https://user-images.githubusercontent.com/8628929/116457238-c27c0d00-a828-11eb-8415-72a9ee5d83a1.png">

**Comment by mikeacjones** [comment]
Proposed fix: https://github.com/OWASP/crAPI/pull/79

**Comment by mikeacjones** [comment]
And this method, which I think is the correct direction ultimately, fixes it by dynamically fetching author data: https://github.com/Noname-SA/crAPI/tree/issue-6-alt

Means that if while using the app someone changes their email or avatar, the change is actually reflected on things they previously posted, rather than using an "at-that-moment" snapshot of who the author is.
